language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - coverage run --source salling_group_holidays setup.py test
after_success:
  - coveralls
